import { WebGLRenderer, type OrthographicCamera, type PerspectiveCamera, Vector2 } from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import { EventDispatcher } from '@f/utils';
import type { Editor } from './Editor';
import { EventBusType } from '../../types';
declare class ViewPort extends EventDispatcher {
    type: string;
    protected editor: Editor;
    protected domElement: HTMLElement;
    protected renderer: WebGLRenderer;
    camera: PerspectiveCamera | OrthographicCamera;
    protected size: Vector2;
    orbitControls: OrbitControls;
    name: string;
    onAfterRender: (editor: Editor, camera: PerspectiveCamera | OrthographicCamera) => void;
    onBeforeRender: (editor: Editor, camera: PerspectiveCamera | OrthographicCamera) => void;
    protected composer: EffectComposer;
    protected eventBus: EventBusType;
    private _active;
    constructor(editor: Editor, camera: PerspectiveCamera | OrthographicCamera, domElement: HTMLElement);
    get active(): boolean;
    set active(value: boolean);
    protected mountEvents(): void;
    protected unmountEvents(): void;
    protected render(): void;
    setSize(width: number, height: number): void;
    getRenderer(): WebGLRenderer;
}
export { ViewPort };
